name: dart2bytecode
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  args: any
  front_end: any
  kernel: any
  vm: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  expect: any
  test: any
