name: profiling
description: Utilities for low-level profiling of Dart code
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
