# Currently, front_end API is not stable and users should not
# depend on semver semantics when depending on this package.
name: front_end

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.3.0-0

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  _fe_analyzer_shared: any
  kernel: any
  macros: any
  package_config: any
  vm: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer: any
  args: any
  build_integration: any
  compiler: any
  dart_style: any
  dart2wasm: any
  dev_compiler: any
  expect: any
  json_rpc_2: any
  path: any
  test_reflective_loader: any
  test: any
  testing: any
  vm_service: any
  web_socket_channel: any

dependency_overrides:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  _js_interop_checks:
    path: ../_js_interop_checks
  build_integration:
    path: ../build_integration
  compiler:
    path: ../compiler
  dart2js_info:
    path: ../dart2js_info
  dart2wasm:
    path: ../dart2wasm
  dev_compiler:
    path: ../dev_compiler
  expect:
    path: ../expect
  js_ast:
    path: ../js_ast
  js_runtime:
    path: ../js_runtime
  js_shared:
    path: ../js_shared
  kernel:
    path: ../kernel
  mmap:
    path: ../mmap
  smith:
    path: ../smith
  testing:
    path: ../testing
  vm:
    path: ../vm
  wasm_builder:
    path: ../wasm_builder
