name: status_file
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  args: any
  path: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  expect: any
  lints: any
