name: vm_service
version: 13.0.0
# TODO(bkonyi): resolve outstanding TODOs required for 13.0.0 release before
# removing.
publish_to: none
description: >-
  A library to communicate with a service implementing the Dart VM
  service protocol.

repository: https://github.com/dart-lang/sdk/tree/main/pkg/vm_service

environment:
  sdk: ^3.0.0

# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  async: any
  collection: any
  expect: any
  lints: any
  markdown: any
  path: any
  pub_semver: any
  test_package: any
  test: any
  vm_service_protos: any

# TODO(bkonyi): remove expect and smith overrides before
# publishing 13.0.0.
dependency_overrides:
  expect:
    path: '../expect'
  smith:
    path: '../smith'
  test_package:
    path: 'test/test_package'
