include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_void_async
    - unawaited_futures
    - require_trailing_commas
    - prefer_relative_imports

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
